version: '3.1'

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
  app:
    links:
      - db
    container_name: web
    build:
      context: .
    env_file:
      - .env
    working_dir: /visualisation
    ports:
      - 3005:3005
    command: npm start
