version: "3.1"

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    env_file:
      - .env
#  for development only
#    ports:
#      - 127.0.0.1:27017:27017
  app:
    links:
      - mongodb
    build:
      context: .
    env_file:
      - .env
    working_dir: /visualisation
    volumes:
      - ./data/files:/visualisation/backend/uploads
    ports:
      - 127.0.0.1:3005:3005
    command: yarn start
