version: "3.1"

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    env_file:
      - .env

  app:
    links:
      - mongodb
    build:
      context: .
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    working_dir: /visualisation
    volumes:
      - ./data/files:/visualisation/backend/uploads
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    command: yarn start
