export const chartConfigOptionTypes = {
  X_AXIS: 'xAxis',
  Y_AXIS: 'yAxis',
  GEO_METRIC_SERIES: 'geoMetricSeries',
  GEO_DIMENSIONS: 'geoDimensions',
  GIS_SHAPE_LAYER: 'gisShapeLayer',
  GIS_REGION_ID: 'gisRegionId',
  GIS_MEASURE: 'gisMeasure',
  SLIDER_CONFIG: 'sliderConfig',
  CHOROPLETH_CONFIG: 'choroplethConfig',
  DATASOURCE: 'dataSource',
  CHART_NAME: 'chartName',
  MEASURE: 'measure',
  ANNOTATION: 'annotation',
  LINE_CHART_SERIES_STYLE: 'lineChartSeriesStyle',
  BAR_CHART_SERIES_STYLE: 'barChartSeriesStyle',
  HISTOGRAM_CHART_SERIES_STYLE: 'harChartSeriesStyle',
  AXIS_CONFIG: 'axisConfig',
  HISTOGRAM_AXIS_CONFIG: 'histogramAxisConfig',
};
