const EXTENDED_JSON_TYPES = ['geojson'];
const VALID_FILE_EXTENSIONS = [...EXTENDED_JSON_TYPES, 'csv'];
const MAX_FILE_SIZE = 314572800;

export { VALID_FILE_EXTENSIONS, MAX_FILE_SIZE, EXTENDED_JSON_TYPES };
